version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    expose:
      - "27017"
    networks:
      - grpc_network
  crud-server:
    container_name: crud-server
    build: server/
    ports:
      - 44441:44441
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - grpc_network
  crud-client:
    container_name: crud-client
    build: frontend/
    ports:
      - 8080:8080
    networks:
      - grpc_network
    environment:
      - CGO_ENABLED=0 
      - GOOS=linux
    depends_on:
      - crud-server
networks: 
  grpc_network:
    name: grpc_network