# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crud_pb2 as crud__pb2


class CRUDStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Insert = channel.unary_unary(
        '/CRUD/Insert',
        request_serializer=crud__pb2.InsertRequest.SerializeToString,
        response_deserializer=crud__pb2.StatusResponse.FromString,
        )


class CRUDServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Insert(self, request, context):
    """RPC Insert Data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CRUDServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Insert': grpc.unary_unary_rpc_method_handler(
          servicer.Insert,
          request_deserializer=crud__pb2.InsertRequest.FromString,
          response_serializer=crud__pb2.StatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CRUD', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
