# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crud_pb2 as crud__pb2


class CRUDStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Insert = channel.unary_unary(
        '/CRUD/Insert',
        request_serializer=crud__pb2.InsertRequest.SerializeToString,
        response_deserializer=crud__pb2.StatusResponse.FromString,
        )
    self.List = channel.unary_stream(
        '/CRUD/List',
        request_serializer=crud__pb2.Empty.SerializeToString,
        response_deserializer=crud__pb2.DataResponse.FromString,
        )
    self.Show = channel.unary_unary(
        '/CRUD/Show',
        request_serializer=crud__pb2.DataId.SerializeToString,
        response_deserializer=crud__pb2.DataResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/CRUD/Update',
        request_serializer=crud__pb2.InsertRequest.SerializeToString,
        response_deserializer=crud__pb2.StatusResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/CRUD/Delete',
        request_serializer=crud__pb2.DataId.SerializeToString,
        response_deserializer=crud__pb2.StatusResponse.FromString,
        )


class CRUDServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Insert(self, request, context):
    """RPC Insert Data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Show(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CRUDServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Insert': grpc.unary_unary_rpc_method_handler(
          servicer.Insert,
          request_deserializer=crud__pb2.InsertRequest.FromString,
          response_serializer=crud__pb2.StatusResponse.SerializeToString,
      ),
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=crud__pb2.Empty.FromString,
          response_serializer=crud__pb2.DataResponse.SerializeToString,
      ),
      'Show': grpc.unary_unary_rpc_method_handler(
          servicer.Show,
          request_deserializer=crud__pb2.DataId.FromString,
          response_serializer=crud__pb2.DataResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=crud__pb2.InsertRequest.FromString,
          response_serializer=crud__pb2.StatusResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=crud__pb2.DataId.FromString,
          response_serializer=crud__pb2.StatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CRUD', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
